title: "Rakhat Nurgali's Professional Website"
author: "Rakhat Nurgali"
description: "Rakhat Nurgali | Finance @ Georgia Tech | FinTech & CS Minor"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false
show_frame: true
show_sidebar: false
minimal: false

# Menu
navigation:
  - {file: "Projects.md", title: "Projects"}
  - {file: "Experience.md", title: "Experience"}
  - {file: "RakhatCV.pdf", title: "CV"}

external:
  - {title: Mail, icon: envelope, url: "mailto:rnurgali3@gatech.edu"}
  - {title: Github, icon: github, url: "https://github.com/rakhatnurgali"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/rakhatnurgali"}

comments:
#  disqus_shortname: ""
#  isso_domain: ""

plugins:
 - jekyll-feed
